# SPDX-License-Identifier: Apache-2.0

FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /complytime-mcp ./cmd/complytime-mcp/

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /complytime-mcp /complytime-mcp

ENTRYPOINT ["/complytime-mcp"]
