// SPDX-License-Identifier: Apache-2.0
//
// Demo template — copy this file and rename it to <change-name>-demo.cy.ts
// for each completed OpenSpec change.
//
// Generated by the skills/cypress-demo skill agent. See SKILL.md for usage.
//
// Prerequisites:
//   - Stack running: make compose-up (or port-forward to cluster)
//   - Demo data seeded: make seed (if applicable)
//   - STUDIO_API_TOKEN env var if auth is enabled
//
// Run:
//   cd demo && npx cypress run --no-runner-ui --spec 'cypress/e2e/<change-name>-demo.cy.ts'

// ---------------------------------------------------------------------------
// Timing constants — adjust if demo runs too fast or slow
// ---------------------------------------------------------------------------
const LONG = 1800;
const PAUSE = 900;
const SHORT = 400;
const TYPE_DELAY = 40;

// ---------------------------------------------------------------------------
// Inline helpers — copy/paste from demo/cypress/support/demo-helpers.ts
// Keep each spec self-contained for portability.
// ---------------------------------------------------------------------------

function setupDemoHelpers(): void {
  cy.document().then((doc) => {
    if (doc.getElementById("__demo_cursor__")) return;

    const cursor = doc.createElement("div");
    cursor.id = "__demo_cursor__";
    Object.assign(cursor.style, {
      position: "fixed",
      width: "18px",
      height: "18px",
      borderRadius: "50%",
      background: "white",
      boxShadow: "0 0 0 2px rgba(0,0,0,0.4), 0 2px 8px rgba(0,0,0,0.5)",
      zIndex: "999999",
      pointerEvents: "none",
      transform: "translate(-50%, -50%)",
      transition: "left 0.4s cubic-bezier(0.4,0,0.2,1), top 0.4s cubic-bezier(0.4,0,0.2,1)",
      left: "960px",
      top: "540px",
    });
    doc.body.appendChild(cursor);

    const bar = doc.createElement("div");
    bar.id = "__demo_caption__";
    Object.assign(bar.style, {
      position: "fixed",
      top: "0",
      left: "0",
      right: "0",
      background: "rgba(15,15,20,0.88)",
      backdropFilter: "blur(6px)",
      color: "#e8e8f0",
      fontFamily: "ui-monospace, 'Cascadia Code', monospace",
      fontSize: "13px",
      padding: "7px 16px",
      zIndex: "1000000",
      pointerEvents: "none",
      letterSpacing: "0.01em",
      display: "none",
    });
    doc.body.appendChild(bar);
  });
}

function caption(text: string): void {
  cy.document().then((doc) => {
    const bar = doc.getElementById("__demo_caption__");
    if (!bar) return;
    bar.style.display = "block";
    bar.textContent = text;
  });
}

function clearCaption(): void {
  cy.document().then((doc) => {
    const bar = doc.getElementById("__demo_caption__");
    if (bar) bar.style.display = "none";
  });
}

function moveTo(selector: string): void {
  cy.get(selector).first().then(($el) => {
    const rect = $el[0].getBoundingClientRect();
    cy.document().then((doc) => {
      const cursor = doc.getElementById("__demo_cursor__");
      if (!cursor) return;
      cursor.style.left = `${rect.left + rect.width / 2}px`;
      cursor.style.top = `${rect.top + rect.height / 2}px`;
    });
  });
  cy.wait(SHORT);
}

function clickEffect(): void {
  cy.document().then((doc) => {
    const cursor = doc.getElementById("__demo_cursor__");
    if (!cursor) return;
    const x = parseFloat(cursor.style.left);
    const y = parseFloat(cursor.style.top);
    const ripple = doc.createElement("div");
    Object.assign(ripple.style, {
      position: "fixed",
      left: `${x}px`,
      top: `${y}px`,
      width: "0px",
      height: "0px",
      borderRadius: "50%",
      border: "3px solid #4f8ef7",
      transform: "translate(-50%, -50%)",
      zIndex: "999998",
      pointerEvents: "none",
      opacity: "1",
      transition: "width 0.5s ease-out, height 0.5s ease-out, opacity 0.5s ease-out",
    });
    doc.body.appendChild(ripple);
    requestAnimationFrame(() => {
      ripple.style.width = "60px";
      ripple.style.height = "60px";
      ripple.style.opacity = "0";
    });
    setTimeout(() => ripple.remove(), 600);
  });
}

function cursorClick(selector: string): void {
  moveTo(selector);
  cy.wait(PAUSE);
  clickEffect();
  cy.get(selector).first().click();
  cy.wait(SHORT);
}

// ---------------------------------------------------------------------------
// TODO: Replace all placeholders below with the change-specific flow.
//
// Checklist:
//   [ ] Rename describe() to match the change name
//   [ ] Update each caption() to narrate what's being shown
//   [ ] Add/remove steps to match the change's happy path
//   [ ] Set the correct selectors for new UI elements
//   [ ] Verify waitForSelector values exist in the rendered DOM
//   [ ] Remove this comment block when done
// ---------------------------------------------------------------------------

describe("<change-name>: <one-line description>", () => {
  before(() => {
    const token = Cypress.env("STUDIO_API_TOKEN") as string | undefined;
    if (token) cy.setCookie("studio_session", token);
    cy.visit("/");
    cy.wait(1000);
    setupDemoHelpers();
  });

  it("demonstrates the feature end-to-end", () => {

    // -----------------------------------------------------------------------
    // Step 1: Orient — where does this feature live?
    // -----------------------------------------------------------------------
    caption("<change-name> — Feature Demo");
    cy.wait(LONG);

    caption("Step 1: <describe what we're orienting the audience to>");
    cy.wait(PAUSE);

    // Navigate to the relevant view via sidebar
    // e.g. cursorClick(".sidebar-item[data-view='posture']");
    // TODO: add navigation

    cy.wait(PAUSE);

    // -----------------------------------------------------------------------
    // Step 2: Demonstrate the primary user action
    // -----------------------------------------------------------------------
    caption("Step 2: <describe the primary action>");
    cy.wait(PAUSE);

    // TODO: interact with the new UI element
    // e.g. cursorClick(".my-new-button");
    //      cy.get(".my-new-panel").should("be.visible");

    cy.wait(LONG);

    // -----------------------------------------------------------------------
    // Step 3: Show the result / artifact
    // -----------------------------------------------------------------------
    caption("Step 3: <describe the outcome>");
    cy.wait(PAUSE);

    // TODO: assert and highlight the result

    cy.wait(LONG);

    clearCaption();
    cy.wait(LONG);
  });
});
