# SPDX-License-Identifier: Apache-2.0
{{- if and .Values.blobStorage.enabled .Values.blobStorage.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.blobStorage.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.blobStorage.accessKey | quote }}
  secret-key: {{ .Values.blobStorage.secretKey | quote }}
{{- end }}
