# SPDX-License-Identifier: Apache-2.0
{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
    {{- include "studio.selectorLabels" (dict "component" "studio-registry" "root" .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "studio.selectorLabels" (dict "component" "studio-registry" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "studio.labels" . | nindent 8 }}
        {{- include "studio.selectorLabels" (dict "component" "studio-registry" "root" .) | nindent 8 }}
    spec:
      containers:
        - name: zot
          image: {{ .Values.registry.image }}
          ports:
            - containerPort: 5000
              name: registry
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
{{- end }}
